config/routes.rb
Rails.application.routes.draw do
  get 'home/index', as: :root
  get 'home/form', as: :form
  post 'home/savform' , to:'home#savform' , as: :formp
  get 'home/project', as: :project
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
  def form
@formp= Home.new

  end
  def savform

  	@f= Home.new(name: params[:home][:name], email: params[:home][:email], phone_no: params[:home][:phone_no] , message: params[:home][:message])

@f.save
redirect_to root_path
  end
  def project
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/form.html.erb
<div class='page-e wow fadeInUp'data-wow-duration="3s">
<br>
<div class="form-edit"> 
<%=form_for @formp ,url:formp_path , method: 'post' do |f|%>
<div class='form-group'> 
	<%=f.label :name%>
	<%=f.text_field :name , class: 'form-control'%>
</div>
<div class='form-group'> 
	<%=f.label :email%>
	<%=f.text_field :email , class: 'form-control'%>
</div>
<div class='form-group'> 
	<%=f.label :mobile_number%>
	<%=f.text_field :phone_no , class: 'form-control'%>
</div>
<div class='form-group'> 
	<%=f.label :message%>
	<%=f.text_area :message , class: 'form-control area'%>
</div>
<%=f.submit 'Submit', class: "btn btn-primary"%>
<%end%>
</div>
</div>

app/views/home/index.html.erb
	
	
		<div class="d-none d-lg-flex" id="mainscreen" style='height:100vh; background-image: url(<%=asset_path("arpitaa.jpg")%>)' >
			<div id="bele">
				
				<p>Welcome To Arpit's World</p>
			</div>
			<span id="binsele"></span>
		</div>
		
		<div class="d-flex d-lg-none" id="mainscreen2" style="height:100vh" >
			<div id="bele">
				
				<p>Welcome To Arpit's World</p>
			</div>
			<span id="binsele"></span>
		</div>
			<span id="binsele"></span>
		</div>
		<div id="quotescreen" style="background-image: url(<%=asset_path("keyboard2.jpg")%>)">
			<p><q>Once a new technology rolls over you, if you're not part of the steamroller, you're part of the road</q>
		<br>
		-Stewart Brand</p>
		</div>

		<div class="d-lg-block d-none" id="about">
			<div  id="aboutbanner">
				<div class="wow fadeInLeft" id="aboutstats">
				<p>	Name: Arpit Sachdeva<br>
					Education: B.Tech in Electrical Engineering (DTU)<br>
					Previous Experience: GirnarSoft(Cardekho.com) , MentorIndia , Coding Ninjas<br></p>
				</div>
				<div class="wow fadeInRight" id="aboutimg">
					<img src="<%=asset_path("pic.jpg")%>">
				</div>
			</div>
			<div class="wow fadeInLeft" id="aboutext">
				<p>
					I am currently pursuing Electrical Engineering from the esteemed Delhi Technological University (formerly Delhi College of Engineering). Within 4 years of my engineering i have acquired various technological skills required today in the market. Have worked with various startups like Cardekho.com, TATA etc for development of their website and technologies. I have always focused on learning and quality development.
				</p>
			</div>
		</div>

		<div class="d-lg-none d-block" id="about2">
			<div  id="aboutbanner">
				<div class="wow fadeInLeft" id="aboutstats">
				<p>	Name: Arpit Sachdeva<br>
					Education: B.Tech in Electrical Engineering (DTU)<br>
					Previous Experience: GirnarSoft(Cardekho.com) , MentorIndia , Coding Ninjas<br></p>
				</div>
				<div class="wow fadeIn" id="aboutimg">
					<img src="<%=asset_path("pic.jpg")%>">
				</div>
			</div>
			<div class="wow fadeInLeft" id="aboutext">
				<p>
					I am currently pursuing Electrical Engineering from the esteemed Delhi Technological University (formerly Delhi College of Engineering). Within 4 years of my engineering i have acquired various technological skills required today in the market. Have worked with various startups like Cardekho.com, TATA etc for development of their website and technologies. I have always focused on learning and quality development.
				</p>
			</div>
		</div>
		<div id="tech" class='d-lg-block d-none'>
			<div class="wow fadeInLeft " data-wow-duration="2s" id="techstack">
				<h2 style="margin-top: 0;padding-top: 2vh;">Technologies-: </h2>
				<div class="techimg">
				<div><img src='<%=asset_path("rails.png")%>' ><h4>Ruby On Rails</h4></div>
				<div><img src='<%=asset_path("html.png")%>'><h4>Html</h4></div>
				<div><img src='<%=asset_path("css2.png")%>'><h4>Css</h4></div>
				<div><img src='<%=asset_path("js2.png")%>'><h4>JavaScript</h4></div>
				<div><img src='<%=asset_path("mb.png")%>'><h4>Matlab</h4></div>
				<div><img src='<%=asset_path("ms.png")%>'><h4>MySQL</h4></div>
				<div><img src='<%=asset_path("j1.png")%>'><h4>jQuery</h4></div>
				<div><img src='<%=asset_path("angular.svg")%>'><h4>Angular.Js</h4></div>
			</div></div>
<br><br>
<div class="wow fadeInRight" data-wow-duration="2s" id="know">
				<h2>Concepts-: </h2>
				<div class="techimg">
				<div><img src='<%=asset_path("ds.png")%>'><h4>Data Structures And Algorithms</h4></div>
				<div><img src='<%=asset_path("os.png")%>'><h4>Operating Systems</h4></div>
				<div><img src='<%=asset_path("dbms.png")%>'><h4>Database Management System</h4></div>
				<div><img src='<%=asset_path("ml.jpg")%>' style="width:60%"><h4>Machine Learning</h4></div>
				</div></div>
		<br><br>
<div class="wow fadeInUp" data-wow-duration="2s" id="program">
				<h2>Languages-: </h2>
				<div class="techimg">
				<div><img src='<%=asset_path("java.png")%>'><h4>Java</h4></div>
				<div><img src='<%=asset_path("ruby.png")%>'><h4>Ruby</h4></div>
				<div><img src='<%=asset_path("cp.png")%>'><h4>C/C++</h4></div>
				
				</div></div>
		<br><br>
		</div>
		<div id="tech2" class='d-lg-none d-block'>
			<div class="wow fadeInDown " data-wow-duration="2s" id="techstack">
				<h2 style="margin-top: 0;padding-top: 2vh;">Technologies-: </h2>
				<div class="techimg">
			<div><img src='<%=asset_path("rails.png")%>' ><h4>Ruby On Rails</h4></div>
				<div><img src='<%=asset_path("html.png")%>'><h4>Html</h4></div>
				<div><img src='<%=asset_path("css2.png")%>'><h4>Css</h4></div>
				<div><img src='<%=asset_path("js2.png")%>'><h4>JavaScript</h4></div>
				<div><img src='<%=asset_path("mb.png")%>'><h4>Matlab</h4></div>
				<div><img src='<%=asset_path("ms.png")%>'><h4>MySQL</h4></div>
				<div><img src='<%=asset_path("j1.png")%>'><h4>jQuery</h4></div>
				<div><img src='<%=asset_path("angular.svg")%>'><h4>Angular.Js</h4></div>
			</div></div>
<br><br>
<div class="wow fadeInLeft" data-wow-duration="2s" id="know">
				<h2>Concepts-: </h2>
				<div class="techimg">
		<div><img src='<%=asset_path("ds.png")%>'><h4>Data Structures And Algorithms</h4></div>
				<div><img src='<%=asset_path("os.png")%>'><h4>Operating Systems</h4></div>
				<div><img src='<%=asset_path("dbms.png")%>'><h4>Database Management System</h4></div>
				<div><img src='<%=asset_path("ml.jpg")%>' style="width:60%"><h4>Machine Learning</h4></div>
				</div></div>
		<br><br>
<div class="wow fadeInUp" data-wow-duration="2s" id="program">
				<h2>Languages-: </h2>
				<div class="techimg">
				<div><img src='<%=asset_path("java.png")%>'><h4>Java</h4></div>
				<div><img src='<%=asset_path("ruby.png")%>'><h4>Ruby</h4></div>
				<div><img src='<%=asset_path("cp.png")%>'><h4>C/C++</h4></div>
				
				</div></div>
		<br><br>
		</div>
		<div id="tech2" class='d-lg-none d-flex'>
		</div>
		<div class="d-lg-flex d-none"id="bottombar">
			
			<a href='https://www.facebook.com/endoarpit'><i class="fab fa-facebook-square"></i></a>
			<a href='https://twitter.com/arpitsachdeva03'>	<i class="fab fa-twitter-square"></i></a>
			<a href='https://www.instagram.com/arpit_03/'><i class="fab fa-instagram"></i></a>
			<a href='https://www.linkedin.com/in/arpit-sachdeva-98154b136'><i class="fab fa-linkedin"></i></a>
			<a href='https://www.github.com/arpit-03'><i class="fab fa-github-square"></i></a>
		</div>
	<div class="d-flex d-lg-none" id="bottombar2">
	
			<a href='https://www.facebook.com/endoarpit'><i class="fab fa-facebook-square"></i></a>
			<a href='https://twitter.com/arpitsachdeva03'>	<i class="fab fa-twitter-square"></i></a>
			<a href='https://www.instagram.com/arpit_03/'><i class="fab fa-instagram"></i></a>
			<a href='https://www.linkedin.com/in/arpit-sachdeva-98154b136'><i class="fab fa-linkedin"></i></a>
			<a href='https://www.github.com/arpit-03'><i class="fab fa-github-square"></i></a>
		</div>
		
		
	
	
	
		<script type="text/javascript">
		$(document).ready(function(){
			   setTimeout(function(){
var typed= new Typed('#binsele',{stringsElement: '#bele',typeSpeed: 90,backSpeed: 50,loop: true});
    },3000);	

		});

		
		</script>

app/views/home/project.html.erb
<br>
<div id="page-p">
	<h2 style="text-align: center">Mailso (Cardekho.com)</h2><br>
	<div class="imgpro">
		<img src="/assets/mailso.jpg">
		<img src="/assets/mailso1.jpg">
	</div>
	<p>Prepared a Website for sending multiple bulk emails in reduced time for Cardekho.com</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arpit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
  </head>

  <body style="background-color: black;" >
    <div id=loading style="background-image: url(<%=asset_path('loader.gif')%>)">
      
      </div>
    <div class="d-lg-flex d-none"id="bar">
      <div id="left"><img src="<%=asset_path('logo.png')%>"></div>
      <div id="right"><ul><li><a href="<%=root_path%>">About</a></li>
    
        <li><a href="<%=root_path%>">Blog</a></li>
                <li><a href="<%=form_path%>">Contact</a></li>        
      </ul></div>
    </div>
       <div class="d-lg-none d-flex"id="bar2">
      <div id="left"><img src="/assets/logo.png"></div>
      <div id="right"><ul><li><a href="<%=root_path%>">About</a></li>
    
        <li><a href="<%=root_path%>">Blog</a></li>
                <li><a href="<%=form_path%>">Contact</a></li>        
      </ul></div>
    </div>
      <%= javascript_include_tag 'application' %>
  <%= yield%>
<script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
$('#loading')[0].style.display='none';
    },4000);
  });
</script>
    <script>
              new WOW().init();
      
  window.onunload = function(){}; 

</script>

  </body>
</html>